kind: pipeline
name: oati_cliente_ci

steps:
  - name: run_sonar_scanner
    image: sonarsource/sonar-scanner-cli:latest
    environment:
      SONAR_HOST_URL:
        from_secret: SONAR_HOST
      SONAR_TOKEN:
        from_secret: SONAR_TOKEN
      SONAR_SCANNER_OPTS: "-Dsonar.working.directory=/tmp/.scannerwork"
    commands:
      - sonar-scanner
    when:
      branch:
        - develop
        - feature/*
        - release/*
      event:
        - push
